//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneCDCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumSongView
    {
        public string SongTitle { get; set; }
        public int SongRating { get; set; }
        public int TrackLengthSeconds { get; set; }
        public int TrackNumber { get; set; }
        public string AlbumTitle { get; set; }
        public int AlbumYear { get; set; }
        public int AlbumRating { get; set; }
        public string GenreName { get; set; }
        public int SongID { get; set; }
        public int GenreId { get; set; }
        public int AlbumId { get; set; }
        public int ArtistId { get; set; }
        public int SongArtistID { get; set; }
    }
}
